ShoppingCartMVC/Ch24ShoppingCartMVC/Controllers/CheckOutController.cs
using Ch24ShoppingCartMVC.Models;
using Ch24ShoppingCartMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ch24ShoppingCartMVC.Controllers
{
    public class CheckOutController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            CartViewModel model = Session["cart"] as CartViewModel;
            //if the model is null, then call the method GetCart
            if (model == null)
            {
                CartModel cm = new CartModel();
                model = cm.GetCart();
            }
            List<CheckOutViewModel> covm = new List<CheckOutViewModel>();
            foreach(var item in model.Cart)
            {
                CheckOutViewModel c = new CheckOutViewModel()
                {
                    ProductID = item.ProductID,
                    Name = item.Name,
                    Quantity =item.Quantity,
                    UnitPrice = item.UnitPrice,
                    TotalPriceEachItem = item.Quantity * item.UnitPrice
                };
                covm.Add(c);
            }
            return View(covm);
        }
        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            TempData["paymentMethod"] = fc["paymentMethod"];
            TempData["shippingAddress"] = fc["shippingAddress"];
            return RedirectToAction("Confirmation");
        }
        [HttpGet]
        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

ShoppingCartMVC/Ch24ShoppingCartMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    @*Create a ViewBag property called Title*@
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Main.css" rel="stylesheet" />
    @RenderSection("css", required: false)
</head>
<body>
    <header><img src="~/Content/Images/banner.jpg" alt="Store" /></header>
    <aside>
        <nav>
            <ul id="menu">
                @*IMPLEMENT THE LINK Home, Order, Cart and ConctactUs
        Home Action method: Index Controller: Home
        Order Action method: Index Controller: Order
        Cart Action method: List Controller: Cart
        Contact Us Action method: Contact Controller: Home
                *@
                <li>@Html.ActionLink("Home", "Index/", "Home")</li>
                <li>@Html.ActionLink("Order", "Index/", "Order")</li>
                <li>@Html.ActionLink("Cart", "Index/", "Cart")</li>
                <li>@Html.ActionLink("Check Out", "Index/", "CheckOut")</li>
                <li>@Html.ActionLink("Contact Us", "Contact/", "Home")</li>
            </ul>
        </nav>
    </aside>
    <section>
        @RenderBody()
    </section>
    <footer>
        @RenderSection("footer", required: false)
        <p id="copyright">&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>        
    </footer>
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/halloween.js" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>